name: build & push charts

on:
  push:
    branches:
      - master

jobs:
  build-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - uses: azure/setup-helm@v4

      - run: helm repo add helm-apps https://helm-apps.github.io/lib

      - name: Helm dependency update
        run: helm dependency update charts/ssl-pinning

      - name: Lint
        run: helm lint charts/ssl-pinning

      - name: Run chart-releaser
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          config: cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
